INSERT INTO public.users (name, email, password, role, roles, payment_methods) VALUES 
('Yapes Nixon', 'yapes@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Thifshana Jeyabalan', 'thifshana@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Thenushan Suresh', 'thenushan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Tharijanan Arunthavaseelan', 'tharijanan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Suresh Kirusthiya', 'kirusthiya@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Suntharalingam Sutharsan', 'sutharsan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Sivakumar Sanjeevan', 'sanjeevan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Shankavi vijayakumar', 'shankavi@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Saludeen Mohamed Rowsas', 'rowsas@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Saif Ahmed', 'saif@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Saboor Mohaideen Abdul Baasith', 'baasith@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Regunathan Dhanushkar', 'dhanushkar@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Ramanathan Danuharan', 'danuharan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Rajasekaram Mathusan', 'mathusan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Poovilingam Thamsan', 'thamsan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Parameshwararaj Yadhurshana', 'yadhurshana@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Parameshwararaj Kavishna', 'kavishna@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Paramananthan Thanuraj', 'thanuraj@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Paramananthan Dapiyshanth', 'dapi@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Nobert Nilaxshan', 'nilaxshan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Nivethiga Sivakadacham', 'nivethiga@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Ms.Dharsika Satchithanantham', 'dharsika@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Mathiyalagan Pirakeerthan', 'pirakeerthanan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Mahendran kajaatharan', 'kaja@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Lavanya Jegathasa', 'lavanya@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('kunasika Thiyakarasa', 'kunasika@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Kalaimakan Gobithas', 'kalai@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Eswaran Tharmithan', 'tharmithan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Enok bilshan', 'enok@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Ashokkumar Natheesan', 'natheesan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Aravinthan Thivaharan', 'thivaharan@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly']),
('Abitha Amirthalingam', 'abitha@eval.com', '$2b$10$51OHkCA0ITuqE0uR2JQQmug5AOihu8EKa/MRTRJWVbeoms1jY5yTy', 'incubator_staff', ARRAY['incubator_staff'], ARRAY['monthly'])
ON CONFLICT (email) DO UPDATE SET password = EXCLUDED.password, role = EXCLUDED.role, roles = EXCLUDED.roles, payment_methods = EXCLUDED.payment_methods;